<a href="https://colab.research.google.com/github/mfmachado/adar/blob/main/segment_signal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd
import numpy as np
from scipy.misc import electrocardiogram
fs=1000

ecg = electrocardiogram()
emg = np.random.rand(ecg.shape[0], 1)
rsp = np.random.rand(ecg.shape[0], 1)

df = pd.DataFrame(np.vstack([ecg, emg.ravel(), rsp.ravel()]).T, columns=["ecg", "emg", "rsp"])
df.head(20)

      ecg       emg       rsp
0  -0.245  0.021121  0.556370
1  -0.215  0.916440  0.262997
2  -0.185  0.775640  0.261850
3  -0.175  0.240859  0.630469
4  -0.170  0.790088  0.256651
5  -0.170  0.034138  0.351809
6  -0.185  0.843638  0.578672
7  -0.170  0.575963  0.568844
8  -0.160  0.990527  0.433411
9  -0.150  0.397297  0.491123
10 -0.170  0.767712  0.330043
11 -0.205  0.585474  0.111845
12 -0.220  0.049475  0.332641
13 -0.230  0.032333  0.970076
14 -0.210  0.284688  0.132213
15 -0.190  0.156680  0.144891
16 -0.175  0.175430  0.693862
17 -0.185  0.772280  0.041028
18 -0.190  0.082172  0.113555
19 -0.190  0.635624  0.956523

# Create Segment ID

In [52]:
number_of_segments = df.shape[0]/fs
segment_ids = np.arange(1, number_of_segments+1)
segment_ids

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108.])

In [53]:
values_segments = np.repeat(segment_ids, fs)
values_segments

array([  1.,   1.,   1., ..., 108., 108., 108.])

In [54]:
df["segment_id"] = values_segments
df

          ecg       emg       rsp  segment_id
0      -0.245  0.641141  0.314662         1.0
1      -0.215  0.872359  0.783915         1.0
2      -0.185  0.593443  0.893910         1.0
3      -0.175  0.041363  0.010892         1.0
4      -0.170  0.954300  0.664864         1.0
...       ...       ...       ...         ...
107995 -0.440  0.458243  0.679484       108.0
107996 -0.440  0.222389  0.584791       108.0
107997 -0.405  0.528550  0.405372       108.0
107998 -0.395  0.341900  0.780442       108.0
107999 -0.385  0.998935  0.958642       108.0

[108000 rows x 4 columns]

# Group by segment

In [60]:
df_group_segment = df.groupby("segment_id").apply(lambda x: pd.Series([list(x["ecg"]), list(x["emg"]), list(x["rsp"])],
                                                                      index=["ecg", "emg", "rsp"]))

df_group_segment

,ecg,emg,rsp
segment_id,,,
1.0,"[-0.245, -0.215, -0.185, -0.175, -0.17, -0.17,...","[0.6411413688833146, 0.8723593973584024, 0.593...","[0.31466158378067655, 0.7839149989333439, 0.89..."
2.0,"[-0.4, -0.37, -0.355, -0.43, -0.54, -0.61, -0....","[0.3664821444236007, 0.25072719561429846, 0.85...","[0.5077009579753953, 0.5385948165624715, 0.333..."
3.0,"[-0.9, -0.895, -0.895, -0.92, -0.925, -0.915, ...","[0.07871660695270799, 0.006294804456504988, 0....","[0.6774137259188117, 0.15051647964447767, 0.52..."
4.0,"[0.55, 0.565, 0.57, 0.595, 0.615, 0.625, 0.615...","[0.04181589947938835, 0.7087198322798199, 0.68...","[0.21904605770928998, 0.633693443383679, 0.566..."
5.0,"[-0.585, -0.565, -0.56, -0.56, -0.555, -0.545,...","[0.8197632604515992, 0.33156717497254384, 0.12...","[0.6699605714038205, 0.007926053183121229, 0.3..."
...,...,...,...
104.0,"[-0.11, -0.12, -0.15, -0.18, -0.18, -0.185, -0...","[0.3027054151563021, 0.8578527575793905, 0.676...","[0.6931380734522996, 0.7385567245133187, 0.942..."
105.0,"[-0.04, -0.04, -0.045, -0.025, -0.005, 0.0, 0....","[0.6798400512880592, 0.6525994854990751, 0.639...","[0.5638380246741123, 0.6256868330590014, 0.102..."
106.0,"[-0.145, -0.12, -0.095, -0.035, 0.03, 0.105, 0...","[0.4071792595866712, 0.8498593910024584, 0.030...","[0.26241878187528267, 0.46268995961403125, 0.6..."
107.0,"[-0.35, -0.35, -0.325, -0.345, -0.32, -0.31, -...","[0.8888517126216606, 0.3292633476791288, 0.012...","[0.08009819145923802, 0.6389307523467234, 0.46..."
108.0,"[-0.66, -0.66, -0.66, -0.64, -0.635, -0.645, -...","[0.5509889985019298, 0.5569121808238391, 0.679...","[0.1334364638395723, 0.9405375318101378, 0.071..."

# Feature Extraction

In [61]:
df_group_segment["ecg"].apply(np.mean)

segment_id
1.0     -0.293525
2.0     -0.340040
3.0      0.117790
4.0     -0.136395
5.0     -0.626760
           ...
104.0   -0.102000
105.0   -0.206665
106.0   -0.178195
107.0   -0.204805
108.0   -0.227365
Name: ecg, Length: 108, dtype: float64